set noerrorbells
set nowrap
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent
set encoding=utf-8
set mouse=a
set scrolloff=8
set cursorline
set cursorcolumn
set nu rnu
set noswapfile
set nobackup
set undodir=~/.config/nvim/undodir
set undofile
set ignorecase
set smartcase
set incsearch
set hlsearch
set updatetime=300
set cmdheight=2
set formatoptions-=cro
set nrformats=
set colorcolumn=80
set splitright
set lazyredraw
set termguicolors
